{
  "comments": [
    {
      "key": {
        "uuid": "da20952f_4f2684bb",
        "filename": "nodepool/nodepool.py",
        "patchSetId": 10
      },
      "lineNbr": 2221,
      "author": {
        "id": 6039
      },
      "writtenOn": "2015-09-02T20:49:26Z",
      "side": 1,
      "message": "This should be logged at a higher level than debug, I think warning is an appropriate level.",
      "revId": "472a4034f3989db1f5cd066b1598043bebc55cca",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "da20952f_6f290889",
        "filename": "nodepool/nodepool.py",
        "patchSetId": 10
      },
      "lineNbr": 2228,
      "author": {
        "id": 6039
      },
      "writtenOn": "2015-09-02T20:49:26Z",
      "side": 1,
      "message": "I think this should be an info log message",
      "revId": "472a4034f3989db1f5cd066b1598043bebc55cca",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "da20952f_c6d02c56",
        "filename": "nodepool/nodepool.py",
        "patchSetId": 10
      },
      "lineNbr": 2228,
      "author": {
        "id": 6133
      },
      "writtenOn": "2015-09-03T07:34:02Z",
      "side": 1,
      "message": "that is not related with my change, maybe we leave for a followup patch?",
      "parentUuid": "da20952f_6f290889",
      "revId": "472a4034f3989db1f5cd066b1598043bebc55cca",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "fa1b9901_9d9a356d",
        "filename": "nodepool/nodepool.py",
        "patchSetId": 10
      },
      "lineNbr": 2233,
      "author": {
        "id": 7069
      },
      "writtenOn": "2015-08-20T12:15:42Z",
      "side": 1,
      "message": "I\u0027m confused why this is here? Aren\u0027t the previous checks for the provider protecting against this?",
      "revId": "472a4034f3989db1f5cd066b1598043bebc55cca",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "fa1b9901_c876a9d6",
        "filename": "nodepool/nodepool.py",
        "patchSetId": 10
      },
      "lineNbr": 2233,
      "author": {
        "id": 13252
      },
      "writtenOn": "2015-08-20T12:45:33Z",
      "side": 1,
      "message": "IIUC the node may have been deleted externally, say by some admin doing \"nova delete\", but it will still be in the database. So we want to catch this exception and continue to the \"remove from database\" part below instead of failing.\n\nAlso note this code part is not new with this patch, just shuffled around a bit.",
      "parentUuid": "fa1b9901_9d9a356d",
      "revId": "472a4034f3989db1f5cd066b1598043bebc55cca",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "fa1b9901_f1580e8c",
        "filename": "nodepool/nodepool.py",
        "patchSetId": 10
      },
      "lineNbr": 2233,
      "author": {
        "id": 6133
      },
      "writtenOn": "2015-08-21T06:41:06Z",
      "side": 1,
      "message": "Yes, it comes from a previous review. So we only allow the provider manager exception to be accepted, and the others to pass.\njens is right with his comments.",
      "parentUuid": "fa1b9901_c876a9d6",
      "revId": "472a4034f3989db1f5cd066b1598043bebc55cca",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "da20952f_0f208c9a",
        "filename": "nodepool/nodepool.py",
        "patchSetId": 10
      },
      "lineNbr": 2238,
      "author": {
        "id": 6039
      },
      "writtenOn": "2015-09-02T20:49:26Z",
      "side": 1,
      "message": "This should also be an info log message",
      "revId": "472a4034f3989db1f5cd066b1598043bebc55cca",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "da20952f_e6d3f05d",
        "filename": "nodepool/nodepool.py",
        "patchSetId": 10
      },
      "lineNbr": 2238,
      "author": {
        "id": 6133
      },
      "writtenOn": "2015-09-03T07:34:02Z",
      "side": 1,
      "message": "same here",
      "parentUuid": "da20952f_0f208c9a",
      "revId": "472a4034f3989db1f5cd066b1598043bebc55cca",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "da20952f_2f2310a9",
        "filename": "nodepool/nodepool.py",
        "patchSetId": 10
      },
      "lineNbr": 2264,
      "author": {
        "id": 6039
      },
      "writtenOn": "2015-09-02T20:49:26Z",
      "side": 1,
      "message": "This can potentially create a key with a None image_name, do we want to only update statsd if we have a valid image_name?",
      "revId": "472a4034f3989db1f5cd066b1598043bebc55cca",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "da20952f_e63a1098",
        "filename": "nodepool/nodepool.py",
        "patchSetId": 10
      },
      "lineNbr": 2264,
      "author": {
        "id": 6133
      },
      "writtenOn": "2015-09-03T07:34:02Z",
      "side": 1,
      "message": "Done",
      "parentUuid": "da20952f_2f2310a9",
      "revId": "472a4034f3989db1f5cd066b1598043bebc55cca",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    }
  ]
}