{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "c5e099c3_24a13f29",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 9
      },
      "lineNbr": 0,
      "author": {
        "id": 35923
      },
      "writtenOn": "2024-08-02T08:33:31Z",
      "side": 1,
      "message": "Seeing the same exception and not released  nodes until launcher restart in our environment. Thanks for fix, will also check on our side later.",
      "revId": "9336a76f6348b7e07d7d98b8b6996d81ee8a478c",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    }
  ]
}