{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "06fb2e1d_1a00076d",
        "filename": "nodepool/cmd/nodepoolcmd.py",
        "patchSetId": 14
      },
      "lineNbr": 303,
      "author": {
        "id": 1
      },
      "writtenOn": "2022-10-11T15:41:55Z",
      "side": 1,
      "message": "If I\u0027m following correctly, trying to delete a locked node is now non-fatal?  Or am I missing something?  If not, then I don\u0027t think that\u0027s a change we should make.",
      "revId": "b16a1d8bfe32fbe0dc21752562b5d14d889a29cc",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "b1457123_7c42ad8e",
        "filename": "nodepool/cmd/nodepoolcmd.py",
        "patchSetId": 14
      },
      "lineNbr": 326,
      "author": {
        "id": 1
      },
      "writtenOn": "2022-10-11T15:41:55Z",
      "side": 1,
      "message": "Similarly to deleting, it seems like if we are unable to lock a node, the command should exit non-zero?",
      "revId": "b16a1d8bfe32fbe0dc21752562b5d14d889a29cc",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "2e4edfa1_f6e9a642",
        "filename": "nodepool/cmd/nodepoolcmd.py",
        "patchSetId": 14
      },
      "lineNbr": 326,
      "author": {
        "id": 35200
      },
      "writtenOn": "2022-10-11T17:28:29Z",
      "side": 1,
      "message": "Not sure if I understand. I don\u0027t see the delete function or any other command return non-zero anywhere.",
      "parentUuid": "b1457123_7c42ad8e",
      "revId": "b16a1d8bfe32fbe0dc21752562b5d14d889a29cc",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "efd7aafd_e1d98d21",
        "filename": "nodepool/cmd/nodepoolcmd.py",
        "patchSetId": 14
      },
      "lineNbr": 326,
      "author": {
        "id": 1
      },
      "writtenOn": "2022-10-11T18:18:31Z",
      "side": 1,
      "message": "My understanding (and I haven\u0027t run this locally to double check, so correct me if I\u0027m wrong) is that the current code will raise an exception if we run \"nodepool delete\" on a locked node.  Raising the exception will cause the CLI to exit rc\u003d1.  And some versions of this patch do the same for the \"hold\" command, which I think is the best behavior, but my concern with this version is that it would only print a statement that the node was locked and then exit rc\u003d0 because the exception was suppressed (and the same applied to delete).\n\nAnyway, to be clear, I think the best behavior for both delete and hold is to try to lock the node and exit with an error code if that fails.",
      "parentUuid": "2e4edfa1_f6e9a642",
      "revId": "b16a1d8bfe32fbe0dc21752562b5d14d889a29cc",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "2ba062ca_6a87d189",
        "filename": "nodepool/cmd/nodepoolcmd.py",
        "patchSetId": 14
      },
      "lineNbr": 326,
      "author": {
        "id": 35200
      },
      "writtenOn": "2022-10-11T18:30:13Z",
      "side": 1,
      "message": "\u003e the current code will raise an exception if we run \"nodepool delete\" on a locked node.  Raising the exception will cause the CLI to exit rc\u003d1\n\nI see now, I thought you were referring to some explicit return 1 or something like that in the code.\nPS15 should behave as you describe now, exiting with an error if locking a node fails",
      "parentUuid": "efd7aafd_e1d98d21",
      "revId": "b16a1d8bfe32fbe0dc21752562b5d14d889a29cc",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "01b52bec_2e696b64",
        "filename": "nodepool/tests/unit/test_commands.py",
        "patchSetId": 14
      },
      "lineNbr": 436,
      "author": {
        "id": 1
      },
      "writtenOn": "2022-10-11T15:41:55Z",
      "side": 1,
      "message": "What is this tiny sleep for?",
      "revId": "b16a1d8bfe32fbe0dc21752562b5d14d889a29cc",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "889ab349_6f769e83",
        "filename": "nodepool/tests/unit/test_commands.py",
        "patchSetId": 14
      },
      "lineNbr": 470,
      "author": {
        "id": 1
      },
      "writtenOn": "2022-10-11T15:41:55Z",
      "side": 1,
      "message": "As I mentioned in the previous patchset, because of the paralellism in unit tests, we need longer delays in order for the test to be valid.",
      "revId": "b16a1d8bfe32fbe0dc21752562b5d14d889a29cc",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    }
  ]
}